Add markupsafe==2.0.1 to requirement.txt
This fixes a breaking change reported at
https://github.com/pallets/markupsafe/issues/284.

The errors were showing up in the heroku logs thus:

    2022-02-21T00:47:47.248902+00:00 app[web.1]: from markupsafe import soft_unicode
    2022-02-21T00:47:47.248903+00:00 app[web.1]: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/app/.heroku/python/lib/python3.9/site-packages/markupsafe/__init__.py)